services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
