# fly.toml app configuration file generated for telegrama on 2024-07-19T22:06:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegrama'
primary_region = 'gru'

[build]
dockerfile = './apps/server/Dockerfile'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
